SRC			= archive_tasks.c rps.c cli_server.c  main.c train_server.c train_server_helper.c train_task.c user_tasks.c park_server.c
SRC			+= milestone1_test.c
TARGET_ELF 	= main.elf

all: build $(TARGET_ELF) copy

include ../../common/common.mk

#CFLAGS += -O2
